#!/bin/sh
source ./utils.sh
source ./run_utils.sh
source ./env_var.sh

binding_file=$(get_first_file ~/.config/oscout/bindings ./bindings)

(echo $(get_header)) | fzf --phony --delimiter ':' --ansi \
    --header-lines=2  \
    --bind "$(get_bindings $binding_file | envsubst)" \
    --preview 'highlight_line={2} \
        line_range_begin=$((line = highlight_line - (FZF_PREVIEW_LINES / 4) && line < 1 ? 1 : line)) \
        line_range_end=$((line_range_begin + FZF_PREVIEW_LINES)) && \
        bat --style=numbers --color=always --line-range "$line_range_begin:$line_range_end"\
            --highlight-line {2} {1} 2> /dev/null' \
    --prompt='(g)>'
