#!/bin/sh
source $HOME/.config/oscout/env_var.sh
source $OSCOUT_INSTALL_PATH/env_var.sh
source $HOME/.config/oscout/env_var.sh
export R_UTILS=$OSCOUT_INSTALL_PATH/run_utils.sh
source $OSCOUT_INSTALL_PATH/run_utils.sh

binding_file=$($OSCOUT_INSTALL_PATH/src/get_first_file "$HOME/.config/oscout/bindings" "${OSCOUT_INSTALL_PATH}/bindings")


(echo $(get_header)) | fzf --phony --delimiter ':' --ansi \
    --header-lines=2  \
    --bind "$($OSCOUT_INSTALL_PATH/src/get_bindings ${binding_file} | envsubst)" \
    --preview '$OSCOUT_INSTALL_PATH/src/preview {1} {2}' \
    --prompt='(g)>'
